In [1]:
import torch
from torch import nn
import numpy as np
import matplotlib.pyplot as plt
import sklearn.model_selection

Python basics

In [6]:
d1 = np.random.rand(2,3)
print('np array:' '\n', d1)

t1 = torch.tensor(d1)
print('tensor:' '\n', t1)

d2 = t1.numpy()

print('back to np array:' '\n', d2)

np array:
 [[0.82193489 0.8187419  0.89158224]
 [0.7302311  0.16222177 0.12517206]]
tensor:
 tensor([[0.8219, 0.8187, 0.8916],
        [0.7302, 0.1622, 0.1252]], dtype=torch.float64)
back to np array:
 [[0.82193489 0.8187419  0.89158224]
 [0.7302311  0.16222177 0.12517206]]


Tensor basics

In [12]:
#Tensors are simple to create:
tensorOfZeros = torch.zeros([2,4], dtype=torch.int32)
print('tensor of zeros:' '\n', tensorOfZeros)

tensorFromNumpy = torch.tensor(np.random.rand(1, 3), dtype=torch.float32)
print('tensor from numpy:' '\n', tensorFromNumpy)

tensor of zeros:
 tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)
tensor from numpy:
 tensor([[0.2420, 0.7687, 0.1940]])


In [18]:
newShape = tensorFromNumpy.reshape((3,1))
print(newShape)
print(newShape.sum(dim=0))
print(newShape.float())

tensor([[0.2420],
        [0.7687],
        [0.1940]])
tensor([1.2047])
tensor([[0.2420],
        [0.7687],
        [0.1940]])


Tensor basics - autograd

In [19]:
#The reason why pyutorch and tensors are actually smart, is autograd:
w = torch.tensor(2.0, requires_grad=True)

x = torch.rand((2,2))

x2 = x*w

L = torch.sum(x2, axis=(0,1))
print(w.grad)

None


In [20]:
L.retain_grad()
x2.retain_grad()
L.backward(retain_graph=True)
print(w.grad)

tensor(2.1236)


In [21]:
print(x.grad)
print(x2.grad)
print(L.grad)

None
tensor([[1., 1.],
        [1., 1.]])
tensor(1.)


Dataset and dataloader

In [ ]:
#tensor with 2000 data points, each data point is a 3x4 random matrix
data_tensor_X = torch.rand((2000, 3, 4))

#ylabels (targets), 2000 integers from 0 to 3:
data_tensor_y = torch.randint(low=0, high=4, size=(2000,))

#we combine X and y in the same dataset:

trainDataset = torch.utils.data.TensorDataset(data_tensor_X, data_tensor_y)

trainDataLoader = torch.utils.dataLoader(trainDataset, batch_sioze=32)

#it is now very easy to iterate over the training data:
#This wont run as the net and loss functions has not been defined yet
for xbatch, ybatch in trainDataLoader:
    y_pred = net.forward(xbatch) #calculate network output
    loss = loss_fn(y_pred, y_miniBatch) #calculate loss for the output
    
    net.zero_grad()
    
    loss.backward() #Backprop
    optimizer.step()
    